### ISSUE TITLE
Esqueceu de definir atributos como private

### ISSUE THREAD

**Issue by manoelcampos** [silvioantonio/produto-builder#1]
Se não tá usando uma biblioteca como Quarkus, não tem porque deixar os atributos como package.
Mas tá ok.

https://github.com/silvioantonio/produto-builder/blob/ed99b07cbd665bbb2d8db97e8148d47619980819/src/main/java/com/silvio/exercicio/builder/ProdutoBuilder.java#L8

**Comment by manoelcampos** [comment]
Na verdade entendi. É pq vc quer acessar os atributos de dentro de Produto, passando a builder por parâmetro.

**Comment by silvioantonio** [comment]
Exatamente, e nesse caso especifico, foi a forma mais tranquila que achei de contornar esse problema...
